### ISSUE TITLE
Скрытие меню в трее

### ISSUE THREAD

**Issue by 7OH** [infostart-hub/core_as_loader#10]
Если нажал правой кнопкой на стартере и не хочешь ничего выбирать - отказаться от выбора невозможно.
На других приложениях клик на панели убирает менюху.
Пока приходится выбирать "о программе".
Надо бы поправить.

**Comment by orefkov** [comment]
Сам уже с этим сталкивался. Пробую разобраться.
С уважением, Александр Орефков


ср, 8 сент. 2021 г. в 09:54, Semion ***@***.***>:
